name: Pull Request Validation
on:
  pull_request:
    branches:
      - develop
jobs:
  linting-job:
    name: Lint HTML and CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --save-dev htmlhint stylelint
      - name: Lint HTML Files
        run: npx htmlhint "*/.html"
      - name: Lint CSS Files
        run: npx stylelint "*/.css"

  build-job:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install parcel
      - name: Build Website
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"