name: liniting-wf
on:
  pull_request:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install HTMLHint
        run: npm install --save-dev htmlhint 
      - name: Install stylelint 
        run: npm install --sase-dev stylelint 
      - name: Lint Htnl Files
        run: npx htmlhint "**/*.html"
      - name: Lint css Files
        run: npx stylelint "**/*.css"
      - name: Display Package.json Contents
        run: cat package.json

  build-job:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install parcel
      - name: Build Website
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"